url = "http://ftp.gnu.org/gnu/bash/bash-5.1.8.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []


[intel]
checksum = '16b6b87bb4f292ff74f4b73f548aeb9fde8ee2711cbf11e5730a83ec50a1da78'

[silicon]
checksum = '7fdc0bcf903da71c2fd099e21b053d4fe0ce487340279c968fd534a5e139a53b'
